name: TODO

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  todos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: derjuulsn/todo-issue@main
        with:
          excludePattern: '(node_modules/)'
          autoAssign: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.SOURCE_PUSH_TOKEN }}
